CREATE TABLE `chantiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`statut` enum('demande','analyse','offre_envoyee','documents_demandes','validation_admin','autorise','en_cours','volume_atteint','cloture','refuse') NOT NULL DEFAULT 'demande',
	`societeNom` varchar(255) NOT NULL,
	`societeAdresse` text NOT NULL,
	`societeTva` varchar(30) NOT NULL,
	`societeMail` varchar(320) NOT NULL,
	`societeContact` varchar(255) NOT NULL,
	`societeTelephone` varchar(30) NOT NULL,
	`localisationChantier` text NOT NULL,
	`contactChantier` varchar(255) NOT NULL,
	`telephoneChantier` varchar(30) NOT NULL,
	`volumeEstime` float NOT NULL,
	`classe` int NOT NULL,
	`periodeDebut` varchar(10) NOT NULL,
	`periodeFin` varchar(10) NOT NULL,
	`prixTonne` decimal(10,2),
	`conditionsAcceptation` text,
	`confirmationClient` boolean DEFAULT false,
	`dateConfirmation` varchar(10),
	`referenceWalterre` varchar(100),
	`certificatQualite` boolean DEFAULT false,
	`rapportAnalyse` boolean DEFAULT false,
	`volumeDeclare` float,
	`regimeApplicable` varchar(100),
	`transporteurs` text,
	`validationClasse` boolean DEFAULT false,
	`validationCertificat` boolean DEFAULT false,
	`validationRapport` boolean DEFAULT false,
	`validationRegime` boolean DEFAULT false,
	`validationVolume` boolean DEFAULT false,
	`dateAutorisation` varchar(10),
	`motifRefusAdmin` text,
	`dateRefus` varchar(10),
	`tonnageAccepte` float NOT NULL DEFAULT 0,
	`tonnageRefuse` float NOT NULL DEFAULT 0,
	`notes` text,
	`createdByUserId` int,
	`dateCreation` timestamp NOT NULL DEFAULT (now()),
	`dateMaj` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `chantiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `incidents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`type` enum('camion_refuse','suspicion_post_deversement','autre') NOT NULL,
	`statut` enum('ouvert','en_cours','resolu') NOT NULL DEFAULT 'ouvert',
	`chantierId` int NOT NULL,
	`chantierNom` varchar(255) NOT NULL,
	`passageId` int,
	`date` varchar(10) NOT NULL,
	`description` text NOT NULL,
	`photoUrl` text,
	`zoneIsolee` boolean DEFAULT false,
	`clientInforme` boolean DEFAULT false,
	`dateResolution` varchar(10),
	`resoluParUserId` int,
	`resoluParNom` varchar(255),
	`notesResolution` text,
	`historiqueActions` text,
	`notes` text,
	`createdByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `incidents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `passages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`chantierId` int NOT NULL,
	`chantierNom` varchar(255) NOT NULL,
	`date` varchar(10) NOT NULL,
	`heure` varchar(5) NOT NULL,
	`plaque` varchar(20) NOT NULL,
	`transporteur` varchar(255) NOT NULL,
	`referenceChantier` varchar(100) NOT NULL,
	`tonnage` float NOT NULL,
	`accepte` boolean NOT NULL,
	`motifRefus` varchar(50),
	`motifRefusDetail` text,
	`photoUrl` text,
	`bonWalterreOk` boolean,
	`referenceOk` boolean,
	`plaqueOk` boolean,
	`correspondanceOk` boolean,
	`controleVisuelOk` boolean,
	`anomalies` text,
	`operateurId` int,
	`operateurNom` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `passages_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `users` ADD `appRole` enum('gestionnaire','prepose') DEFAULT 'gestionnaire';